language: shell
cache: pip

matrix:
  include:      
    - name: "Python 3.7 on macOS 10.14"
      os: osx
      osx_image: xcode11.3
      language: shell
      env:
        - export PATH="/usr/local/opt/flex/bin:$PATH"
        - export LDFLAGS="-L/usr/local/opt/flex/lib:$LDFLAGS"
        - export CPPFLAGS="-I/usr/local/opt/flex/include:$CPPFLAGS"
        - export PATH="/usr/local/opt/bison/bin:$PATH"
        - export LDFLAGS="-L/usr/local/opt/bison/lib:$LDFLAGS"

    - name: "Python 3.7 on xenial"
      os: linux
      dist: xenial
      language: python
      python: 3.7

before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest
install:
  - cd deps
  - git clone https://github.com/QE-Lab/libqasm.git
  - cd libqasm
  - pip install . 
  - cd ..
  - git clone https://github.com/QE-Lab/eQASM_Assembler.git
  - cd eQASM_Assembler/qisa-as
  - pip install .
  - cd ../../../.
  - pip install .
script: python3 -m pytest

addons:
  apt:
    packages:
      - cmake
      - swig
      - flex
      - bison
  homebrew:
    packages:
      - cmake
      - swig
      - flex
      - bison
    update: true
